In [1]:
import os
import GEOparse
import pandas as pd

# Get GEO_ID from parent folder name
GEO_ID = os.path.basename(os.path.dirname(os.path.abspath('__file__')))

gse = GEOparse.get_GEO(geo=GEO_ID, silent=True)

# map sample title to metadata
metadata = {}

for key, value in gse.gsms.items():
    sample_title = value.metadata['title'][0]

    metadata_object = {'sample_title': sample_title}
    for item in value.metadata['characteristics_ch1']:
        k, v = item.split(':', 1)
        metadata_object[k.strip()] = v.strip()

    metadata[key] = metadata_object


metadata_df = pd.DataFrame.from_dict(metadata, orient='index')
metadata_df.index.name = 'samples'
# metadata_df = metadata_df.reset_index()

# Filter out rows where prognostic subtype is the string 'NA'
filtered_metadata_df = metadata_df[metadata_df['prognostic subtype'] != 'NA']

print(filtered_metadata_df.shape)
filtered_metadata_df

(46, 7)

,sample_title,tissue,gender,age,survival time,survival,prognostic subtype
samples,,,,,,,
GSM4998233,2004-950RNAseq,Brain Metastatic Tissue,Male,67,35.8,1,Poor
GSM4998234,2006-262-RNAseq,Brain Metastatic Tissue,Male,55,1,0,Good
GSM4998235,2006-76RNASeq,Brain Metastatic Tissue,Male,61,1.1,1,Good
GSM4998236,2007-109RNASeq,Brain Metastatic Tissue,Female,61,3.2,1,Good
GSM4998237,2007-263-RNAseq,Brain Metastatic Tissue,Female,61,2.6,1,Good
GSM4998238,2007-45RNAseq,Brain Metastatic Tissue,Female,45,8.6,1,Cluster 1
GSM4998239,2007-550RNAseq,Brain Metastatic Tissue,Female,81,58,0,Poor
GSM4998240,2007-563RNAseq,Brain Metastatic Tissue,Female,47,113.2,0,Poor
GSM4998241,2007-601RNAseq,Brain Metastatic Tissue,Female,47,10,1,Others
GSM4998242,2008-1840RNAseq,Brain Metastatic Tissue,Male,55,29.1,1,Others
GSM4998243,2009-1104RNAseq,Brain Metastatic Tissue,Male,54,16.5,1,Good
GSM4998244,2009-451RNAseq,Brain Metastatic Tissue,Female,62,6.5,1,Good
GSM4998245,2012-1354-RNAseq,Brain Metastatic Tissue,Female,56,8.5,1,Good
GSM4998246,2012-1430RNAseq,Brain Metastatic Tissue,Male,73,34,0,Poor
GSM4998247,2012-1807RNAseq,Brain Metastatic Tissue,Female,70,6.9,1,Good
GSM4998248,2013-1795RNAseq,Brain Metastatic Tissue,Female,74,0.1,0,Cluster 2
GSM4998249,2013-2873RNAseq,Brain Metastatic Tissue,Female,69,1.5,1,Others
GSM4998250,2014-1511RNAseq,Brain Metastatic Tissue,Female,64,3.4,1,Good
GSM4998251,2015-109RNAseq,Brain Metastatic Tissue,Female,37,3.8,1,Others
GSM4998252,2015-1335RNAseq,Brain Metastatic Tissue,Male,51,23.2,0,Poor
GSM4998253,2015-1834RNAseq,Brain Metastatic Tissue,Male,67,0.9,0,Others
GSM4998254,2015-955RNAseq,Brain Metastatic Tissue,Male,71,1.2,1,Good
GSM4998256,4482RNAseq,Brain Metastatic Tissue,Male,57,1.4,0,Cluster 1
GSM4998257,4497RNAseq,Brain Metastatic Tissue,Female,67,6,1,Others
GSM4998258,4500RNAseq,Brain Metastatic Tissue,Female,52,1.4,0,Cluster 1
GSM4998259,4512RNAseq,Brain Metastatic Tissue,Female,69,2.7,0,Cluster 1
GSM4998260,4526RNAseq,Brain Metastatic Tissue,Female,57,7.1,0,Others
GSM4998261,4558RNASeq,Brain Metastatic Tissue,Female,69,0.7,0,Good
GSM4998262,4559-RNAseq,Brain Metastatic Tissue,Male,57,2.3,1,Cluster 1
GSM4998263,4567RNAseq,Brain Metastatic Tissue,Female,51,8.1,1,Others
GSM4998264,4578RNASeq,Brain Metastatic Tissue,Male,45,18.2,1,Others
GSM4998265,4579RNASeq,Brain Metastatic Tissue,Female,44,25.6,0,Cluster 2
GSM4998266,4582RNASeq,Brain Metastatic Tissue,Female,58,0,0,Good
GSM4998267,4588RNASeq,Brain Metastatic Tissue,Male,66,2.8,0,Cluster 1
GSM4998268,4595RNASeq,Brain Metastatic Tissue,Male,62,0.1,0,Others
GSM4998269,4632RNASeq,Brain Metastatic Tissue,Female,47,27.4,1,Poor
GSM4998270,4636RNAseq,Brain Metastatic Tissue,Male,48,3.3,0,Cluster 2
GSM4998271,4671RNASeq,Brain Metastatic Tissue,Female,59,0,0,Cluster 2
GSM4998272,4687RNASeq,Brain Metastatic Tissue,Male,65,34.2,1,Poor
GSM4998273,4722-RNAseq,Brain Metastatic Tissue,Male,71,89,0,Poor
GSM4998274,4739RNASeq,Brain Metastatic Tissue,Male,76,3.2,0,Others
GSM4998275,4826RNASeq,Brain Metastatic Tissue,NA,NA,NA,NA,Cluster 1
GSM4998276,4931RNAseq,Brain Metastatic Tissue,Male,56,3.9,1,Cluster 1
GSM4998277,4945RNAseq,Brain Metastatic Tissue,Female,28,3.9,1,Others
GSM4998278,4952RNAseq,Brain Metastatic Tissue,Female,51,21,0,Poor
GSM4998279,4955RNAseq,Brain Metastatic Tissue,Female,67,4.3,1,Good

# Use NCBI provided expression data

In [2]:
# Raw counts
ncbi_data_url = f"https://www.ncbi.nlm.nih.gov/geo/download/?type=rnaseq_counts&acc={GEO_ID}&format=file&file={GEO_ID}_raw_counts_GRCh38.p13_NCBI.tsv.gz"


df_raw_counts: pd.DataFrame = pd.read_csv(ncbi_data_url, sep='\t', index_col=0, compression='gzip')
df_raw_counts = df_raw_counts.T
df_raw_counts.index.name = "samples"
df_raw_counts.columns.name = None

url = "https://www.ncbi.nlm.nih.gov/geo/download/?format=file&type=rnaseq_counts&file=Human.GRCh38.p13.annot.tsv.gz"
df_gene_annotations = pd.read_csv(
    url,
    sep="\t",
    compression="gzip"
)
gene_mapping = (
    df_gene_annotations[["GeneID", "Symbol"]]
    .dropna(subset=["GeneID", "Symbol"])
    .set_index("GeneID")["Symbol"]
    .to_dict()
)
# Keep only columns that have a mapping
mappable = [c for c in df_raw_counts.columns if c in gene_mapping]
df_raw_counts = df_raw_counts[mappable].rename(columns=gene_mapping)
# df_raw_counts = df_raw_counts.rename(columns=gene_mapping)


df_combined = metadata_df.join(df_raw_counts, how='inner')
df_combined.reset_index()


data_file_name = f'{GEO_ID}_raw_counts_NCBI.csv'
df_combined.reset_index()
df_combined.to_csv(data_file_name, index=False)

df_combined

/var/folders/h1/fnfx16m50jvd8ddpcs93g9mw0000gn/T/ipykernel_98340/3050319327.py:11: DtypeWarning: Columns (8,9) have mixed types. Specify dtype option on import or set low_memory=False.
  df_gene_annotations = pd.read_csv(

,sample_title,tissue,gender,age,survival time,survival,prognostic subtype,DDX11L1,WASH7P,MIR6859-1,...,ND4,TRNH,TRNS2,TRNL2,ND5,ND6,TRNE,CYTB,TRNT,TRNP
samples,,,,,,,,,,,,,,,,,,,,,
GSM4998233,2004-950RNAseq,Brain Metastatic Tissue,Male,67,35.8,1,Poor,4,173,5,...,3013,20,21,18,1981,323,64,2783,44,536
GSM4998234,2006-262-RNAseq,Brain Metastatic Tissue,Male,55,1,0,Good,9,204,11,...,31743,29,33,28,20092,1861,657,18557,118,1158
GSM4998235,2006-76RNASeq,Brain Metastatic Tissue,Male,61,1.1,1,Good,3,337,6,...,6032,13,12,10,5681,650,337,6278,22,756
GSM4998236,2007-109RNASeq,Brain Metastatic Tissue,Female,61,3.2,1,Good,0,146,6,...,10508,41,40,31,5531,609,248,10292,95,1309
GSM4998237,2007-263-RNAseq,Brain Metastatic Tissue,Female,61,2.6,1,Good,14,355,16,...,56838,173,187,168,44605,2439,616,37793,256,832
GSM4998238,2007-45RNAseq,Brain Metastatic Tissue,Female,45,8.6,1,Cluster 1,6,82,0,...,2998,20,16,14,2298,274,90,2867,96,382
GSM4998239,2007-550RNAseq,Brain Metastatic Tissue,Female,81,58,0,Poor,7,294,10,...,6387,30,35,26,4762,581,161,6691,80,299
GSM4998240,2007-563RNAseq,Brain Metastatic Tissue,Female,47,113.2,0,Poor,6,271,5,...,4696,14,12,11,3166,355,128,3470,74,597
GSM4998241,2007-601RNAseq,Brain Metastatic Tissue,Female,47,10,1,Others,4,187,3,...,3056,19,23,14,2239,351,129,3436,59,437
GSM4998242,2008-1840RNAseq,Brain Metastatic Tissue,Male,55,29.1,1,Others,1,124,1,...,7854,27,28,18,5558,595,193,9478,51,388
GSM4998243,2009-1104RNAseq,Brain Metastatic Tissue,Male,54,16.5,1,Good,6,709,29,...,226225,452,409,340,173125,17997,2669,100202,1015,2979
GSM4998244,2009-451RNAseq,Brain Metastatic Tissue,Female,62,6.5,1,Good,7,245,7,...,22136,18,22,17,14162,1035,380,9384,50,227
GSM4998245,2012-1354-RNAseq,Brain Metastatic Tissue,Female,56,8.5,1,Good,24,434,40,...,44108,68,69,56,32984,3540,1029,23765,128,1034
GSM4998246,2012-1430RNAseq,Brain Metastatic Tissue,Male,73,34,0,Poor,4,395,8,...,5623,16,18,21,4135,402,108,5122,14,141
GSM4998247,2012-1807RNAseq,Brain Metastatic Tissue,Female,70,6.9,1,Good,14,182,6,...,32430,254,230,106,25764,2561,1001,18155,1048,5540
GSM4998248,2013-1795RNAseq,Brain Metastatic Tissue,Female,74,0.1,0,Cluster 2,6,180,6,...,14801,74,66,61,11303,1139,413,11880,627,1640
GSM4998249,2013-2873RNAseq,Brain Metastatic Tissue,Female,69,1.5,1,Others,5,209,3,...,37601,23,22,14,25262,1985,737,35730,178,2076
GSM4998250,2014-1511RNAseq,Brain Metastatic Tissue,Female,64,3.4,1,Good,13,294,12,...,26045,91,84,55,12952,1704,576,14558,422,1981
GSM4998251,2015-109RNAseq,Brain Metastatic Tissue,Female,37,3.8,1,Others,5,73,2,...,24728,22,19,11,10503,1309,341,15973,96,1175
GSM4998252,2015-1335RNAseq,Brain Metastatic Tissue,Male,51,23.2,0,Poor,32,320,11,...,65276,95,90,81,41688,4243,1227,46422,333,2851
GSM4998253,2015-1834RNAseq,Brain Metastatic Tissue,Male,67,0.9,0,Others,14,394,13,...,48843,215,192,166,35732,4193,1080,25858,1295,3057
GSM4998254,2015-955RNAseq,Brain Metastatic Tissue,Male,71,1.2,1,Good,6,287,29,...,65833,39,36,28,29907,3564,1111,31686,196,2363
GSM4998255,33-4559RNASeq,Brain Metastatic Tissue,NA,NA,NA,NA,NA,5,165,6,...,3502,21,26,28,3513,435,140,2293,97,413
GSM4998256,4482RNAseq,Brain Metastatic Tissue,Male,57,1.4,0,Cluster 1,3,153,0,...,6160,17,18,16,2889,401,121,2615,69,539
GSM4998257,4497RNAseq,Brain Metastatic Tissue,Female,67,6,1,Others,9,173,4,...,5946,19,31,37,3193,379,120,2916,49,184
GSM4998258,4500RNAseq,Brain Metastatic Tissue,Female,52,1.4,0,Cluster 1,4,220,7,...,5324,25,28,23,3301,574,278,4616,70,522
GSM4998259,4512RNAseq,Brain Metastatic Tissue,Female,69,2.7,0,Cluster 1,8,164,2,...,4885,26,28,16,2855,357,109,4445,175,709
GSM4998260,4526RNAseq,Brain Metastatic Tissue,Female,57,7.1,0,Others,3,155,5,...,4660,19,19,16,3554,298,134,4496,82,252
GSM4998261,4558RNASeq,Brain Metastatic Tissue,Female,69,0.7,0,Good,6,183,5,...,4702,39,112,167,3786,1499,202,3430,88,483
GSM4998262,4559-RNAseq,Brain Metastatic Tissue,Male,57,2.3,1,Cluster 1,8,261,4,...,6058,36,51,53,6010,846,229,4100,160,593
GSM4998263,4567RNAseq,Brain Metastatic Tissue,Female,51,8.1,1,Others,3,100,2,...,6349,42,38,23,6091,768,230,5719,158,516
GSM4998264,4578RNASeq,Brain Metastatic Tissue,Male,45,18.2,1,Others,6,92,2,...,4576,29,107,150,3703,995,181,3488,113,435
GSM4998265,4579RNASeq,Brain Metastatic Tissue,Female,44,25.6,0,Cluster 2,4,120,2,...,3629,19,20,14,2520,282,124,4056,140,738
GSM4998266,4582RNASeq,Brain Metastatic Tissue,Female,58,0,0,Good,2,148,5,...,4380,30,27,17,3794,276,86,3820,57,217
GSM4998267,4588RNASeq,Brain Metastatic Tissue,Male,66,2.8,0,Cluster 1,7,190,9,...,2263,15,17,7,1811,174,77,2257,114,546
GSM4998268,4595RNASeq,Brain Metastatic Tissue,Male,62,0.1,0,Others,2,110,9,...,4194,21,17,13,3574,462,171,3807,38,443
GSM4998269,4632RNASeq,Brain Metastatic Tissue,Female,47,27.4,1,Poor,5,126,1,...,3176,20,21,11,2012,227,81,3020,81,442
GSM4998270,4636RNAseq,Brain Metastatic Tissue,Male,48,3.3,0,Cluster 2,10,173,3,...,3472,21,26,21,2931,275,115,2855,83,281
GSM4998271,4671RNASeq,Brain Metastatic Tissue,Female,59,0,0,Cluster 2,5,187,4,...,7505,41,45,30,6659,874,331,7518,420,1998
GSM4998272,4687RNASeq,Brain Metastatic Tissue,Male,65,34.2,1,Poor,10,200,3,...,7388,43,47,22,5107,683,258,6383,187,1113
GSM4998273,4722-RNAseq,Brain Metastatic Tissue,Male,71,89,0,Poor,3,171,3,...,18037,33,35,28,10914,1285,425,12232,544,1731
GSM4998274,4739RNASeq,Brain Metastatic Tissue,Male,76,3.2,0,Others,15,256,8,...,3995,25,23,13,3341,441,201,3561,84,657
GSM4998275,4826RNASeq,Brain Metastatic Tissue,NA,NA,NA,NA,Cluster 1,1,129,1,...,3316,15,14,7,1738,263,98,4021,72,604
GSM4998276,4931RNAseq,Brain Metastatic Tissue,Male,56,3.9,1,Cluster 1,6,321,1,...,28028,52,46,41,11723,1730,491,16046,337,3366
GSM4998277,4945RNAseq,Brain Metastatic Tissue,Female,28,3.9,1,Others,9,222,10,...,13312,28,37,30,7443,1432,307,9211,162,739
GSM4998278,4952RNAseq,Brain Metastatic Tissue,Female,51,21,0,Poor,8,232,8,...,14536,27,28,32,9282,1186,222,12500,83,753
GSM4998279,4955RNAseq,Brain Metastatic Tissue,Female,67,4.3,1,Good,5,188,17,...,22979,43,38,22,13515,1364,356,16757,191,1016

In [3]:
import json
import os
import sys
from pathlib import Path

project_root = Path().resolve().parent.parent  # adjust based on notebook depth
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from geo.scripts.generate_descriptions import generate_description_from_geo

description_file_path = 'description.json'


if not os.path.exists(description_file_path):
    with open(description_file_path, 'w') as f:
        json.dump({}, f)

with open(description_file_path, 'r') as f:
    desc_data = json.load(f)

if not desc_data:
    desc_data = generate_description_from_geo(GEO_ID)

desc_data['data_summary'] = {
    'samples': df_combined.shape[0],
    'clinical_features': metadata_df.shape[1],
    'genes': df_raw_counts.shape[1]
}
print("Description updated")

desc_data['data_file_names'] = [data_file_name]

with open(description_file_path, "w") as f:
    json.dump(desc_data, f, indent=4)

Description updated