In [1]:
import os
import GEOparse
import pandas as pd


# Get GEO_ID from parent folder name
GEO_ID = os.path.basename(os.path.dirname(os.path.abspath('__file__')))

gse = GEOparse.get_GEO(geo=GEO_ID, silent=True)

# map sample title to metadata
metadata = {}

for key, value in gse.gsms.items():
    sample_title = value.metadata['title'][0]

    metadata_object = {"sample_title": sample_title}
    for item in value.metadata['characteristics_ch1']:
        k, v = item.split(':')
        metadata_object[k.strip()] = v.strip()

    metadata[key] = metadata_object


# Create metadata DataFrame and join as columns to df_genes (rows=samples)
metadata_df = pd.DataFrame.from_dict(metadata, orient='index')
metadata_df.index.name = 'samples'

# Apply the cohort-selection rules from the paper:
# 1) keep only secondary high-grade glioma samples (grade == HGG)
# 2) remove low-quality samples with uniquely mapped reads < 30%
# 3) if a patient has multiple runs, keep the run with best mapping quality
col_map = 'percentage of uniquely mapped reads'

metadata_df = (
    metadata_df
    .assign(
        # Normalize fields used in filtering/sorting to avoid type/whitespace issues.
        grade=lambda d: d['grade'].astype(str).str.strip(),
        **{col_map: lambda d: pd.to_numeric(d[col_map])},
        **{'patient id': lambda d: d['patient id'].astype(str).str.strip()},
    )
    # Apply diagnosis + QC criteria in one step.
    .query("grade == 'HGG' and `percentage of uniquely mapped reads` >= 30")
    # Sort so best-quality sample (highest mapping rate) is first per patient.
    .sort_values(['patient id', col_map], ascending=[True, False])
    # Keep exactly one sample per patient.
    .drop_duplicates('patient id', keep='first')
    .copy()
)

In [2]:
# Sanity checks for cohort selection
print(f"Final selected rows: {metadata_df.shape[0]}")
print(f"Unique patients: {metadata_df['patient id'].nunique()}")
print(f"Duplicate patient IDs remaining: {metadata_df['patient id'].duplicated().sum()}")
print(
    "Min unique mapping (%): "
    f"{metadata_df['percentage of uniquely mapped reads'].min():.2f}"
)

Final selected rows: 60
Unique patients: 60
Duplicate patient IDs remaining: 0
Min unique mapping (%): 31.59

# Use NCBI provided expression data

In [3]:
# Raw counts
ncbi_data_url = f"https://www.ncbi.nlm.nih.gov/geo/download/?type=rnaseq_counts&acc={GEO_ID}&format=file&file={GEO_ID}_raw_counts_GRCh38.p13_NCBI.tsv.gz"

df_raw_counts: pd.DataFrame = pd.read_csv(ncbi_data_url, sep='\t', index_col=0, compression='gzip')
df_raw_counts = df_raw_counts.T
df_raw_counts.index.name = "samples"
df_raw_counts.columns.name = None

url = "https://www.ncbi.nlm.nih.gov/geo/download/?format=file&type=rnaseq_counts&file=Human.GRCh38.p13.annot.tsv.gz"
df_gene_annotations = pd.read_csv(
    url,
    sep="\t",
    compression="gzip"
)
gene_mapping = (
    df_gene_annotations[["GeneID", "Symbol"]]
    .dropna(subset=["GeneID", "Symbol"])
    .set_index("GeneID")["Symbol"]
    .to_dict()
)
# Keep only columns that have a mapping
mappable = [c for c in df_raw_counts.columns if c in gene_mapping]
df_raw_counts = df_raw_counts[mappable].rename(columns=gene_mapping)
# df_raw_counts = df_raw_counts.rename(columns=gene_mapping)

data_file_name = f'{GEO_ID}_raw_counts_NCBI.csv'
df_combined = metadata_df.join(df_raw_counts, how='inner')


df_combined.reset_index()
df_combined.to_csv(data_file_name, index=False)

df_combined

/var/folders/h1/fnfx16m50jvd8ddpcs93g9mw0000gn/T/ipykernel_1569/1012403528.py:10: DtypeWarning: Columns (8,9) have mixed types. Specify dtype option on import or set low_memory=False.
  df_gene_annotations = pd.read_csv(

,sample_title,tissue,unique sample id,patient id,grade,batch,idh status prediction,age,date of birth,vital status,...,ND4,TRNH,TRNS2,TRNL2,ND5,ND6,TRNE,CYTB,TRNT,TRNP
samples,,,,,,,,,,,,,,,,,,,,,
GSM5600930,Sample_S-10-33895_S22_L003merged,Glioma,Sample_S-10-33895,1,HGG,1,Mutant,22,3/9/1979,1,...,20285,98,157,122,14226,3986,791,9529,34,614
GSM5600825,Sample_R378-14-133900_S12_L002,Glioma,Sample_14-133900,10,HGG,2,WT,39,2/24/1970,1,...,14107,32,51,43,8383,1300,309,4762,61,1948
GSM5600933,Sample_S-12-53702_S22_L003merged,Glioma,Sample_S-12-53702,103,HGG,1,WT,59,8/12/1950,1,...,50527,227,329,258,40088,6765,1448,20185,153,2319
GSM5600934,Sample_S-13-16523_S22_L003merged,Glioma,Sample_S-13-16523,104,HGG,1,Mutant,31,2/11/1966,1,...,68629,192,291,288,50834,10367,1439,38179,123,1110
GSM5600826,Sample_R378-15-49530_S13_L002,Glioma,Sample_15-49530,11,HGG,2,Mutant,49,1/21/1956,0,...,7757,52,117,113,5845,1466,247,4186,47,807
GSM5600769,Sample_16-647051_S49_L005,Glioma,Sample_16-647051,12,HGG,3,Mutant,20,1/21/1986,1,...,48912,114,157,100,34258,7266,2305,20248,138,6669
GSM5600770,Sample_17-276430_S51_L006,Glioma,Sample_17-276430,13,HGG,3,Mutant,51,5/3/1956,0,...,29135,181,203,119,14702,1083,372,18499,178,2771
GSM5600828,Sample_R378-17-329452_S15_L002,Glioma,Sample_17-329452,14,HGG,2,Mutant,32,8/23/1978,0,...,64896,106,94,54,26187,3565,463,37503,119,6730
GSM5600773,Sample_18-280601_S42_L005,Glioma,Sample_18-280601,15,HGG,2,Mutant,56,7/31/1954,1,...,85674,502,853,598,27707,3642,846,50929,177,16484
GSM5600829,Sample_R378-19-473907_S16_L002,Glioma,Sample_19-473907,16,HGG,2,WT,65,12/7/1940,1,...,9607,50,73,84,8764,3135,350,4252,34,681
GSM5600917,Sample_S-12-91302_S54_L008,Glioma,Sample_S-12-91302,17,HGG,1,Mutant,30,6/15/1977,1,...,12084,70,93,73,8087,1294,482,8052,129,1801
GSM5600784,Sample_24-86073_S48_L005,Glioma,Sample_24-86073,23,HGG,2,Mutant,35,1/4/1971,0,...,17212,22,31,23,9730,1267,274,9768,41,887
GSM5600836,Sample_R378-26-720984_S22_L003,Glioma,Sample_26-720984,25,HGG,2,Mutant,30,8/31/1980,0,...,132068,453,677,450,79057,18152,3959,89860,796,35431
GSM5600837,Sample_R378-27-474275_S23_L003,Glioma,Sample_27-474275,26,HGG,2,Mutant,35,9/2/1969,1,...,70485,486,590,369,54002,10000,1344,54305,535,5980
GSM5600838,Sample_R378-28-474461_S24_L003,Glioma,Sample_28-474461,27,HGG,2,Mutant,29,11/5/1973,0,...,35392,758,1465,1076,28785,19019,5009,4761,105,11107
GSM5600789,Sample_29-347647_S53_L006,Glioma,Sample_29-347647,28,HGG,2,Mutant,31,1/29/1978,1,...,69006,608,854,551,33426,5607,1238,40356,739,31484
GSM5600801,Sample_4-928505_S53_L006,Glioma,Sample_4-928505,29,HGG,3,Mutant,52,10/27/1965,0,...,48428,195,228,166,30643,4774,1354,36217,325,7438
GSM5600822,Sample_R378-10-130792_S9_L002,Glioma,Sample_10-130792,3,HGG,2,Mutant,25,3/29/1984,0,...,45351,174,211,118,28853,4014,1467,35473,178,6815
GSM5600840,Sample_R378-30-355527_S25_L004,Glioma,Sample_30-355527,31,HGG,2,Mutant,33,5/21/1979,1,...,28612,87,102,72,14752,1576,319,17963,124,4718
GSM5600843,Sample_R378-33-91963_S28_L004,Glioma,Sample_33-91963,32,HGG,2,Mutant,34,9/27/1971,1,...,38753,305,342,188,27163,5157,1681,28263,296,8707
GSM5600844,Sample_R378-34-493226_S29_L004,Glioma,Sample_34-493226,33,HGG,2,Mutant,44,8/9/1956,0,...,15689,179,335,252,15235,6763,1083,6254,71,1316
GSM5600795,Sample_35-288330_S59_L007,Glioma,Sample_35-288330,34,HGG,2,Mutant,23,6/22/1985,0,...,57554,98,165,138,28841,3042,898,28015,180,7575
GSM5600846,Sample_R378-37-129347_S31_L004,Glioma,Sample_37-129347,36,HGG,2,Mutant,55,12/30/1951,1,...,17304,166,244,164,11367,4749,794,9015,148,2028
GSM5600847,Sample_R378-38-53636_S32_L004,Glioma,Sample_38-53636,37,HGG,2,Mutant,50,8/5/1953,0,...,16974,150,253,194,10676,3178,726,9458,93,2324
GSM5600799,Sample_39-481640_S63_L007,Glioma,Sample_39-481640,38,HGG,2,Mutant,48,5/2/1960,1,...,17301,130,237,198,10981,1072,276,11430,157,1850
GSM5600758,Sample_10-840737_S57_L007,Glioma,Sample_10-840737,4,HGG,3,Mutant,21,7/28/1982,0,...,49479,236,279,204,23640,4453,965,28910,229,5454
GSM5600802,Sample_40-836221_S64_L007,Glioma,Sample_40-836221,40,HGG,2,Mutant,27,9/26/1983,0,...,25046,47,77,55,11835,1574,520,18464,67,3603
GSM5600849,Sample_R378-41-878541_S33_L005,Glioma,Sample_41-878541,41,HGG,2,Mutant,42,8/30/1968,1,...,18684,161,268,178,11739,2472,764,14927,137,6194
GSM5600850,Sample_R378-42-322918_S34_L005,Glioma,Sample_42-322918,42,HGG,2,Mutant,35,9/9/1959,1,...,10041,206,304,203,7155,1899,557,4804,139,2245
GSM5600805,Sample_43-653001_S67_L008,Glioma,Sample_43-653001,43,HGG,2,Mutant,37,3/28/1970,0,...,46066,150,194,111,24040,2365,706,33950,178,5243
GSM5600806,Sample_44-856139_S68_L008,Glioma,Sample_44-856139,44,HGG,2,Mutant,29,4/14/1980,0,...,38876,268,342,177,25212,3012,481,36755,408,12206
GSM5600851,Sample_R378-45-479502_S35_L005,Glioma,Sample_45-479502,45,HGG,2,Mutant,54,5/17/1950,1,...,3788,17,18,14,2883,472,92,2050,41,472
GSM5600852,Sample_R378-46-493319_S36_L005,Glioma,Sample_46-493319,46,HGG,2,Mutant,NA,1/23/1969,1,...,19710,1020,1523,1043,33021,11336,2676,6063,294,2827
GSM5600809,Sample_47-92626_S71_L008,Glioma,Sample_47-92626,47,HGG,2,Mutant,57,1/17/1945,1,...,14298,157,255,202,11662,3192,383,7922,95,1740
GSM5600853,Sample_R378-48-475866_S37_L005,Glioma,Sample_48-475866,48,HGG,2,Mutant,40,6/21/1960,1,...,8344,40,44,37,6112,1238,187,5183,27,950
GSM5600912,Sample_S-09-3532_S53_L008,Glioma,Sample_S-09-3532,50,HGG,1,Mutant,35,10/28/1967,0,...,21031,50,130,122,12467,3475,439,6625,40,264
GSM5600818,Sample_8-653019_S63_L007,Glioma,Sample_8-653019,52,HGG,3,Mutant,34,11/11/1969,1,...,74109,129,149,117,44224,6900,1274,36772,142,8607
GSM5600819,Sample_9-493777_S33_L004,Glioma,Sample_9-493777,55,HGG,2,Mutant,18,8/1/1985,0,...,7144,25,115,90,5027,524,114,4128,25,525
GSM5600827,Sample_R378-16-773952_S14_L002,Glioma,Sample_16-773952,56,HGG,2,WT,60,6/2/1953,1,...,22931,195,247,131,12530,2459,569,16509,143,8826
GSM5600833,Sample_R378-22-274878_S19_L003,Glioma,Sample_22-274878,57,HGG,2,Mutant,35,8/29/1974,0,...,76702,332,322,220,39273,8707,1631,40443,332,8746
GSM5600841,Sample_R378-31-496519_S26_L004,Glioma,Sample_31-496519,58,HGG,2,Mutant,22,5/2/1986,1,...,72585,452,540,293,42627,12065,2294,37254,396,12417
GSM5600823,Sample_R378-11-493155_S10_L002,Glioma,Sample_11-493155,6,HGG,2,Mutant,27,9/22/1971,1,...,13940,294,491,356,39249,11465,1760,2617,36,1298
GSM5600857,Sample_R378-50-481380_S34_L003,Glioma,Sample_50-481380,61,HGG,2,NaN,49,4/19/1955,0,...,43559,112,157,112,21342,2279,371,24054,111,4447
GSM5600761,Sample_12-780771_S36_L004,Glioma,Sample_12-780771,7,HGG,2,Mutant,41,11/19/1976,0,...,30890,109,159,87,14471,1626,328,19129,152,4604
GSM5600763,Sample_13-474997_S55_L006,Glioma,Sample_13-474997,8,HGG,3,Mutant,50,2/7/1955,1,...,9687,73,100,77,6837,1338,322,5047,45,428
GSM5600891,Sample_R378-71-38765_S51_L007,Glioma,Sample_71-38765,81,HGG,2,NaN,42,8/20/1959,1,...,2502,39,64,49,2455,1092,261,1207,7,249
GSM5600893,Sample_R378-72-128135_S52_L007,Glioma,Sample_72-128135,82,HGG,2,NaN,31,10/25/1978,1,...,13792,79,120,99,8329,1735,499,9350,35,2480
GSM5600898,Sample_R378-75-359415_S54_L007,Glioma,Sample_75-359415,85,HGG,2,NaN,39,2/20/1973,1,...,13358,80,71,48,8499,976,197,11910,107,1684
GSM5600900,Sample_R378-76-497763_S55_L007,Glioma,Sample_76-497763,86,HGG,2,NaN,30,9/29/1982,0,...,58511,181,219,114,31185,3658,512,41075,195,10960
GSM5600903,Sample_R378-78-834403_S56_L007,Glioma,Sample_78-834403,88,HGG,2,NaN,46,11/18/1967,1,...,30770,274,349,192,19361,2205,774,22011,371,18715
GSM5600927,Sample_S-07-18021_S22_L003merged,Glioma,Sample_S-07-18021,89,HGG,1,Mutant,24,7/19/1976,1,...,57609,777,1067,780,61818,13798,2590,31261,222,2399
GSM5600824,Sample_R378-13-480248_S11_L002,Glioma,Sample_13-480248,9,HGG,2,Mutant,35,7/20/1974,0,...,20920,163,185,103,15614,2514,456,12366,125,1391
GSM5600916,Sample_S-12-31070_S46_L008,Glioma,Sample_S-12-31070,91,HGG,1,Mutant,29,5/8/1977,0,...,40935,66,112,155,25886,5452,697,8198,61,782
GSM5600918,Sample_S-13-13785_S55_L008,Glioma,Sample_S-13-13785,92,HGG,1,Mutant,32,11/2/1974,1,...,11024,39,52,40,7731,1468,397,7142,111,2679
GSM5600931,Sample_S-11-31466_S22_L003merged,Glioma,Sample_S-11-31466,94,HGG,1,WT,44,1/2/1966,1,...,30891,109,126,84,29104,5123,802,12664,100,1047
GSM5600919,Sample_S-13-44668_S52_L008,Glioma,Sample_S-13-44668,95,HGG,1,Mutant,34,5/26/1962,1,...,37884,57,99,110,26820,5926,679,14968,44,341
GSM5600929,Sample_S-09-40561_S22_L003merged,Glioma,Sample_S-09-40561,96,HGG,1,Mutant,48,4/22/1953,1,...,25832,68,83,63,18282,4056,647,8976,84,212
GSM5600922,Sample_S-03-45665_S22_L003merged,Glioma,Sample_S-03-45665,97,HGG,1,Mutant,29,12/29/1972,1,...,9805,30,61,42,8671,2008,273,5245,2,74

# Generate description

In [4]:
import json
import os
import sys
from pathlib import Path

project_root = Path().resolve().parent.parent  # adjust based on notebook depth
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from geo.scripts.generate_descriptions import generate_description_from_geo

description_file_path = 'description.json'


if not os.path.exists(description_file_path):
    with open(description_file_path, 'w') as f:
        json.dump({}, f)

with open(description_file_path, 'r') as f:
    desc_data = json.load(f)

if not desc_data:
    desc_data = generate_description_from_geo(GEO_ID)

desc_data['data_summary'] = {
    'samples': metadata_df.shape[0],
    'clinical_features': metadata_df.shape[1],
    'genes': df_raw_counts.shape[1]
}

print("Description updated")

desc_data['data_file_names'] = [data_file_name]

with open(description_file_path, "w") as f:
    json.dump(desc_data, f, indent=4)

Description updated

# Use author provided expression data

In [5]:
metadata_df = metadata_df.reset_index()
metadata_df = metadata_df.set_index('sample_title')

raw_exp_url = 'https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE184941&format=file&file=GSE184941%5FRaw%5Fgene%5Fcounts%5Fmatrix%2Etxt%2Egz'

df_raw_exp: pd.DataFrame = pd.read_csv(raw_exp_url, sep='\t', index_col=0, compression='gzip')
df_raw_exp = df_raw_exp[df_raw_exp.index.notna()]
df_raw_exp = df_raw_exp.T
df_raw_exp.index.name = "samples"
df_raw_exp.columns.name = None

df_combined = metadata_df.join(df_raw_exp, how='inner')
df_combined.reset_index()
# INFO: Uncomment to save the data to disk
# df_combined.to_csv(f'{GEO_ID}_raw.csv', index=False)

df_combined

,samples,tissue,unique sample id,patient id,grade,batch,idh status prediction,age,date of birth,vital status,...,ENSG00000198886.2,ENSG00000210176.1,ENSG00000210184.1,ENSG00000210191.1,ENSG00000198786.2,ENSG00000198695.2,ENSG00000210194.1,ENSG00000198727.2,ENSG00000210195.2,ENSG00000210196.2
Sample_S-10-33895_S22_L003merged,GSM5600930,Glioma,Sample_S-10-33895,1,HGG,1,Mutant,22,3/9/1979,1,...,38142,2,0,0,26053,461,0,19026,17,0
Sample_R378-14-133900_S12_L002,GSM5600825,Glioma,Sample_14-133900,10,HGG,2,WT,39,2/24/1970,1,...,30030,422,0,0,17789,196,0,10039,129,0
Sample_S-12-53702_S22_L003merged,GSM5600933,Glioma,Sample_S-12-53702,103,HGG,1,WT,59,8/12/1950,1,...,94812,0,0,0,71512,1658,40,39213,89,60
Sample_S-13-16523_S22_L003merged,GSM5600934,Glioma,Sample_S-13-16523,104,HGG,1,Mutant,31,2/11/1966,1,...,127744,2,0,0,93925,3050,355,74606,51,85
Sample_R378-15-49530_S13_L002,GSM5600826,Glioma,Sample_15-49530,11,HGG,2,Mutant,49,1/21/1956,0,...,14689,469,0,0,9681,602,12,8639,57,42
Sample_16-647051_S49_L005,GSM5600769,Glioma,Sample_16-647051,12,HGG,3,Mutant,20,1/21/1986,1,...,105009,1350,3,19,73672,1565,60,45039,257,191
Sample_17-276430_S51_L006,GSM5600770,Glioma,Sample_17-276430,13,HGG,3,Mutant,51,5/3/1956,0,...,57455,3028,37,128,26788,351,23,38020,227,181
Sample_R378-17-329452_S15_L002,GSM5600828,Glioma,Sample_17-329452,14,HGG,2,Mutant,32,8/23/1978,0,...,132691,2607,6,6,52715,710,0,78905,52,0
Sample_18-280601_S42_L005,GSM5600773,Glioma,Sample_18-280601,15,HGG,2,Mutant,56,7/31/1954,1,...,160603,40,0,0,46847,946,6,102807,61,70
Sample_R378-19-473907_S16_L002,GSM5600829,Glioma,Sample_19-473907,16,HGG,2,WT,65,12/7/1940,1,...,17952,740,0,0,15720,1298,0,9414,4,28
Sample_S-12-91302_S54_L008,GSM5600917,Glioma,Sample_S-12-91302,17,HGG,1,Mutant,30,6/15/1977,1,...,22838,16,0,0,14691,447,44,15691,104,89
Sample_21-765076_S59_L007,GSM5600781,Glioma,Sample_21-765076,21,HGG,3,WT,45,11/2/1972,0,...,67384,1225,4,40,43070,858,29,25518,99,177
Sample_24-86073_S48_L005,GSM5600784,Glioma,Sample_24-86073,23,HGG,2,Mutant,35,1/4/1971,0,...,34118,40,0,0,19249,168,8,20186,45,29
Sample_R378-26-720984_S22_L003,GSM5600836,Glioma,Sample_26-720984,25,HGG,2,Mutant,30,8/31/1980,0,...,256488,2406,10,26,157531,3941,75,189665,1559,254
Sample_R378-27-474275_S23_L003,GSM5600837,Glioma,Sample_27-474275,26,HGG,2,Mutant,35,9/2/1969,1,...,137040,772,0,6,101910,3139,58,113124,557,263
Sample_R378-28-474461_S24_L003,GSM5600838,Glioma,Sample_28-474461,27,HGG,2,Mutant,29,11/5/1973,0,...,59223,462,0,0,44366,6490,95,10597,227,306
Sample_29-347647_S53_L006,GSM5600789,Glioma,Sample_29-347647,28,HGG,2,Mutant,31,1/29/1978,1,...,132350,128,4,0,63670,757,6,81782,1466,143
Sample_4-928505_S53_L006,GSM5600801,Glioma,Sample_4-928505,29,HGG,3,Mutant,52,10/27/1965,0,...,95666,913,2,29,57233,1723,45,74101,171,323
Sample_R378-10-130792_S9_L002,GSM5600822,Glioma,Sample_10-130792,3,HGG,2,Mutant,25,3/29/1984,0,...,90801,1015,0,0,58153,731,16,73789,130,109
Sample_R378-30-355527_S25_L004,GSM5600840,Glioma,Sample_30-355527,31,HGG,2,Mutant,33,5/21/1979,1,...,56897,1428,10,0,28917,326,2,37026,112,71
Sample_R378-33-91963_S28_L004,GSM5600843,Glioma,Sample_33-91963,32,HGG,2,Mutant,34,9/27/1971,1,...,76686,917,2,0,53091,1065,30,59443,507,227
Sample_R378-34-493226_S29_L004,GSM5600844,Glioma,Sample_34-493226,33,HGG,2,Mutant,44,8/9/1956,0,...,28093,202,2,0,23916,2426,19,13559,17,46
Sample_35-288330_S59_L007,GSM5600795,Glioma,Sample_35-288330,34,HGG,2,Mutant,23,6/22/1985,0,...,111369,43,0,0,55154,424,5,56085,230,78
Sample_R378-37-129347_S31_L004,GSM5600846,Glioma,Sample_37-129347,36,HGG,2,Mutant,55,12/30/1951,1,...,34423,1128,0,0,20638,1781,21,19634,149,90
Sample_R378-38-53636_S32_L004,GSM5600847,Glioma,Sample_38-53636,37,HGG,2,Mutant,50,8/5/1953,0,...,33477,1001,0,0,19591,1135,6,20939,92,40
Sample_39-481640_S63_L007,GSM5600799,Glioma,Sample_39-481640,38,HGG,2,Mutant,48,5/2/1960,1,...,31227,12,0,0,17076,362,4,21782,38,13
Sample_10-840737_S57_L007,GSM5600758,Glioma,Sample_10-840737,4,HGG,3,Mutant,21,7/28/1982,0,...,97740,870,0,16,42198,2248,65,59112,88,213
Sample_40-836221_S64_L007,GSM5600802,Glioma,Sample_40-836221,40,HGG,2,Mutant,27,9/26/1983,0,...,48680,94,0,0,23216,130,7,37274,90,25
Sample_R378-41-878541_S33_L005,GSM5600849,Glioma,Sample_41-878541,41,HGG,2,Mutant,42,8/30/1968,1,...,35738,1942,10,0,21326,795,38,29978,163,84
Sample_R378-42-322918_S34_L005,GSM5600850,Glioma,Sample_42-322918,42,HGG,2,Mutant,35,9/9/1959,1,...,18831,370,0,0,11863,631,4,9839,92,42
Sample_43-653001_S67_L008,GSM5600805,Glioma,Sample_43-653001,43,HGG,2,Mutant,37,3/28/1970,0,...,88061,118,0,0,45353,326,1,68282,253,69
Sample_44-856139_S68_L008,GSM5600806,Glioma,Sample_44-856139,44,HGG,2,Mutant,29,4/14/1980,0,...,73420,62,4,0,46114,709,28,73082,584,118
Sample_R378-45-479502_S35_L005,GSM5600851,Glioma,Sample_45-479502,45,HGG,2,Mutant,54,5/17/1950,1,...,7683,230,0,0,5101,158,2,4104,12,52
Sample_R378-46-493319_S36_L005,GSM5600852,Glioma,Sample_46-493319,46,HGG,2,Mutant,NA,1/23/1969,1,...,28549,139,0,0,44779,3764,47,11650,366,141
Sample_47-92626_S71_L008,GSM5600809,Glioma,Sample_47-92626,47,HGG,2,Mutant,57,1/17/1945,1,...,24174,14,0,0,17304,1147,0,16057,57,4
Sample_R378-48-475866_S37_L005,GSM5600853,Glioma,Sample_48-475866,48,HGG,2,Mutant,40,6/21/1960,1,...,17225,724,18,0,11273,421,10,10873,30,81
Sample_S-09-3532_S53_L008,GSM5600912,Glioma,Sample_S-09-3532,50,HGG,1,Mutant,35,10/28/1967,0,...,39194,0,0,0,22845,439,33,13346,44,31
Sample_8-653019_S63_L007,GSM5600818,Glioma,Sample_8-653019,52,HGG,3,Mutant,34,11/11/1969,1,...,155795,865,7,3,92330,1837,26,79051,119,330
Sample_9-493777_S33_L004,GSM5600819,Glioma,Sample_9-493777,55,HGG,2,Mutant,18,8/1/1985,0,...,12988,0,0,0,8602,193,20,8402,16,0
Sample_R378-16-773952_S14_L002,GSM5600827,Glioma,Sample_16-773952,56,HGG,2,WT,60,6/2/1953,1,...,46069,2479,16,12,22775,1055,4,34730,193,54
Sample_R378-22-274878_S19_L003,GSM5600833,Glioma,Sample_22-274878,57,HGG,2,Mutant,35,8/29/1974,0,...,155473,5390,16,12,75828,2788,51,85346,531,82
Sample_R378-31-496519_S26_L004,GSM5600841,Glioma,Sample_31-496519,58,HGG,2,Mutant,22,5/2/1986,1,...,150825,4160,8,7,84346,3980,117,79590,814,166
Sample_R378-11-493155_S10_L002,GSM5600823,Glioma,Sample_11-493155,6,HGG,2,Mutant,27,9/22/1971,1,...,19589,86,0,2,50900,4420,28,5183,0,30
Sample_R378-50-481380_S34_L003,GSM5600857,Glioma,Sample_50-481380,61,HGG,2,NaN,49,4/19/1955,0,...,88880,469,0,10,41573,546,46,50928,120,46
Sample_12-780771_S36_L004,GSM5600761,Glioma,Sample_12-780771,7,HGG,2,Mutant,41,11/19/1976,0,...,56919,88,0,0,25385,395,13,37108,53,364
Sample_13-474997_S55_L006,GSM5600763,Glioma,Sample_13-474997,8,HGG,3,Mutant,50,2/7/1955,1,...,20803,156,0,0,13257,613,15,11259,29,34
Sample_R378-71-38765_S51_L007,GSM5600891,Glioma,Sample_71-38765,81,HGG,2,NaN,42,8/20/1959,1,...,4809,38,0,0,3947,368,4,2636,4,18
Sample_R378-72-128135_S52_L007,GSM5600893,Glioma,Sample_72-128135,82,HGG,2,NaN,31,10/25/1978,1,...,28708,444,0,0,17118,264,20,20124,65,15
Sample_R378-75-359415_S54_L007,GSM5600898,Glioma,Sample_75-359415,85,HGG,2,NaN,39,2/20/1973,1,...,27290,2111,2,0,16280,300,4,24861,95,80
Sample_R378-76-497763_S55_L007,GSM5600900,Glioma,Sample_76-497763,86,HGG,2,NaN,30,9/29/1982,0,...,117005,2245,0,8,63246,588,21,85288,295,32
Sample_R378-78-834403_S56_L007,GSM5600903,Glioma,Sample_78-834403,88,HGG,2,NaN,46,11/18/1967,1,...,60875,2813,24,2,37042,365,3,44169,549,347
Sample_S-07-18021_S22_L003merged,GSM5600927,Glioma,Sample_S-07-18021,89,HGG,1,Mutant,24,7/19/1976,1,...,97636,2,0,0,97277,4122,296,60380,44,66
Sample_R378-13-480248_S11_L002,GSM5600824,Glioma,Sample_13-480248,9,HGG,2,Mutant,35,7/20/1974,0,...,40929,355,8,3,29453,668,8,25863,89,124
Sample_S-12-31070_S46_L008,GSM5600916,Glioma,Sample_S-12-31070,91,HGG,1,Mutant,29,5/8/1977,0,...,76605,0,0,0,48942,1725,205,15383,52,77
Sample_S-13-13785_S55_L008,GSM5600918,Glioma,Sample_S-13-13785,92,HGG,1,Mutant,32,11/2/1974,1,...,20828,16,0,0,14757,338,6,14202,186,100
Sample_S-11-46862_S22_L003merged,GSM5600932,Glioma,Sample_S-11-46862,93,HGG,1,Mutant,42,6/20/1971,1,...,75265,4,0,0,69631,1807,173,48849,61,89
Sample_S-11-31466_S22_L003merged,GSM5600931,Glioma,Sample_S-11-31466,94,HGG,1,WT,44,1/2/1966,1,...,58493,0,0,0,55183,1012,30,25401,111,30
Sample_S-13-44668_S52_L008,GSM5600919,Glioma,Sample_S-13-44668,95,HGG,1,Mutant,34,5/26/1962,1,...,71251,0,0,0,51431,1182,83,29194,47,37
Sample_S-09-40561_S22_L003merged,GSM5600929,Glioma,Sample_S-09-40561,96,HGG,1,Mutant,48,4/22/1953,1,...,48870,0,0,0,33144,528,18,17517,33,62
Sample_S-03-45665_S22_L003merged,GSM5600922,Glioma,Sample_S-03-45665,97,HGG,1,Mutant,29,12/29/1972,1,...,18557,0,0,0,16308,246,5,10621,0,0